# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Fri Mar 24 14:04:21 CDT 2017
#
#/ usage: terminal:banner  --title <>  --content <> 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
#
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while (( "$#" > 0 ))
    do
        OPT="$1"
        case "$OPT" in
            --title) rerun_option_check $# $1; TITLE=$2 ; shift ;;
            --content) rerun_option_check $# $1; CONTENT=$2 ; shift ;;
            # help option
            -|--*?) echo >&2 "unrecognized option: $OPT"
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.

    # Check required options are set
    [[ -z "$TITLE" ]] && { echo >&2 "missing required option: --title" ; return 2 ; }
    [[ -z "$CONTENT" ]] && { echo >&2 "missing required option: --content" ; return 2 ; }
    # If option variables are declared exportable, export them.

    # Make remaining command line options available in 
    export _CMD_LINE="$@"
    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${TITLE:=}
: ${CONTENT:=}
# Default command line to null if not set
: ${_CMD_LINE:=}


