#!/usr/bin/env bash

#/ command: terminal:banner: "highlight with a title output on the terminal"
#/ usage: rerun terminal:banner  --title <>  --content <> 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: TITLE CONTENT

. $RERUN_MODULE_DIR/lib/functions.sh banner || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -

#rerun stubbs:add-command --command banner --module terminal --description 'highlight with a title output on the terminal'
#rerun stubbs:add-option --option title --required true --export false --command banner --module terminal --description 'highlight with a title output on the terminal'
#rerun stubbs:add-option --option content --required true --export false --command banner --module terminal --description 'content for the banner'

banner $TITLE $CONTENT

# Done. Exit with last command exit status.
exit $?

