#!/usr/bin/env bash

#/ command: message:msg_color_dump: "print possible colors"
#/ usage: rerun message:msg_color_dump [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: 

. $RERUN_MODULE_DIR/lib/functions.sh msg_color_dump || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
clr_dump

# Done. Exit with last command exit status.
exit $?

