#!/usr/bin/env bash

#/ command: message:msg_ok: "print a message in green color"
#/ usage: rerun message:msg_ok  --msg <> 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: MSG

. $RERUN_MODULE_DIR/lib/functions.sh msg_ok || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
#rerun stubbs:add-command --module message --command msg_ok --description "print a message in green color"
#rerun stubbs:add-option --option msg --description "the message to print in green color"  --module message --command msg_ok --required true --export false
clr_green "${MSG}"

# Done. Exit with last command exit status.
exit $?

