#!/usr/bin/env bash

#/ command: mongo:is-running: "check if a mongo is running"
#/ usage: rerun mongo:is-running [ --name <mongo>] 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: NAME

. $RERUN_MODULE_DIR/lib/functions.sh is-running || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
#rerun stubbs:add-command --command is-running --module mongo --description "check if a container is running"
#rerun stubbs:add-option --option name --default mongo --required false --export false --command is-running --module mongo --description "name of the container"

rerun docker:is-running --name $NAME

# Done. Exit with last command exit status.
exit $?

