#!/usr/bin/env bash

#/ command: terminal:cmd-banner-end: "create a command output end for easy reading"
#/ usage: rerun terminal:cmd-banner-end [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables:

. $RERUN_MODULE_DIR/lib/functions.sh cmd-banner-end || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
command_banner_end

# Done. Exit with last command exit status.
exit $?

