# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Mon May 22 13:05:53 CDT 2017
#
#/ usage: docker:rmimage  --imagename <> [ --force <false>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
#
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while (( "$#" > 0 ))
    do
        OPT="$1"
        case "$OPT" in
            --imagename) rerun_option_check $# $1; IMAGENAME=$2 ; shift ;;
            --force) rerun_option_check $# $1; FORCE=$2 ; shift ;;
            # help option
            -|--*?) echo >&2 "unrecognized option: $OPT"
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [[ -z "$FORCE" ]] && FORCE="$(rerun_property_get $RERUN_MODULE_DIR/options/force DEFAULT)"
    # Check required options are set
    [[ -z "$IMAGENAME" ]] && { echo >&2 "missing required option: --imagename" ; return 2 ; }
    # If option variables are declared exportable, export them.

    # Make remaining command line options available in 
    export _CMD_LINE="$@"
    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${IMAGENAME:=}
: ${FORCE:=}
# Default command line to null if not set
: ${_CMD_LINE:=}


