#!/usr/bin/env bash

#/ command: mongo:exec-sh: "connect to a mongo shell of a running instance"
#/ usage: rerun mongo:exec-sh [ --name <mongo>] 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: NAME

. $RERUN_MODULE_DIR/lib/functions.sh exec-sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
#rerun stubbs:add-command --command exec-sh --module mongo --description "connect to a mongo shell of a running instance"
#rerun stubbs:add-option --option name --export false --required false --default mongo --command exec-sh --module mongo --description "the name for this conatiner instance"

rerun docker:exec --name $NAME --command mongo
# Done. Exit with last command exit status.
exit $?

